name: ci

env:
  CMAKE_BUILD_PARALLEL_LEVEL: 4
  CTEST_PARALLEL_LEVEL: 0
  CTEST_NO_TESTS_ACTION: error

on:
  push:
    paths:
      - "**.c"
      - "**.patch"
      - "**.cmake"
      - "**/CMakeLists.txt"
      - ".github/workflows/ci.yml"

jobs:

  base:

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - run: cmake -Bbuild
    - run: cmake --build build
    - run: ctest --test-dir build -V

    - name: verify touch does not fail
      run: |
        cmake -E touch main.cpp
        cmake --build build
        ctest --test-dir build -V

    - name: verify clean does not fail
      run: |
        cmake --build build --clean-first
        ctest --test-dir build -V

  msvc:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - run: cmake -Bbuild
    - run: cmake --build build
    - run: ctest --test-dir build -C Debug -V


    - name: verify touch does not fail
      run: |
        cmake -E touch main.cpp
        cmake --build build
        ctest --test-dir build -C Debug -V

    - name: verify clean does not fail
      run: |
        cmake --build build --clean-first
        ctest --test-dir build -C Debug -V

  mingw:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - run: cmake -Bbuild -G "MinGW Makefiles"
    - run: cmake --build build
    - run: ctest --test-dir build -V

    - name: verify touch does not fail
      run: |
        cmake -E touch main.cpp
        cmake --build build
        ctest --test-dir build -V

    - name: verify clean does not fail
      run: |
        cmake --build build --clean-first
        ctest --test-dir build -V
