name: ci

on:
  push:
    paths:
      - "**.c"
      - "**.patch"
      - "**.cmake"
      - "**/CMakeLists.txt"
      - ".github/workflows/ci.yml"

jobs:

  base:

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - &checkout
      uses: actions/checkout@v6

    - &workflow-default
      run: cmake --workflow default

    - &touch
      name: verify touched main.cpp does not fail
      run: cmake -E touch main.cpp

    - *workflow-default

    - &workflow-clean
      name: verify clean does not fail
      run: cmake --workflow clean

  msvc:
    runs-on: windows-latest

    steps:
    - *checkout

    - &msvc
      run: cmake --workflow msvc

    - *touch
    - *msvc

    - name: verify clean does not fail
      run: |
        cmake --workflow msvc-clean

  mingw:
    runs-on: windows-latest

    steps:
    - *checkout

    - *workflow-default

    - *touch
    - *workflow-default

    - *workflow-clean
